spring.profiles.active: dev

mybatis:
  mapper-locations: classpath:cn/theproudsoul/justwriteitservice/dao/*.xml
  type-aliases-package: cn.theproudsoul.justwriteitservice.model
  configuration.map-underscore-to-camel-case: true

spring:
  datasource:
    name: mysql
    url: jdbc:mysql://localhost:3306/justwriteit?characterEncoding=utf-8&serverTimezone=UTC
    username: justwriteit
    password: justwriteit
    type: com.alibaba.druid.pool.DruidDataSource

server:
  port: 9999

logging:
  level:
    sql: DEBUG